steps:
  - name: 'maven:3.9.6-amazoncorretto-21-debian'
    entrypoint: mvn
    args:
      - package
      - '--batch-mode'
      - '-Dmaven.test.skip=true'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'europe-west1-docker.pkg.dev/progress-january2024/evgeni/personapi:$COMMIT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west1-docker.pkg.dev/progress-january2024/evgeni/personapi:$COMMIT_SHA'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - personapi
      - '--image'
      - 'europe-west1-docker.pkg.dev/progress-january2024/evgeni/personapi:$COMMIT_SHA'
      - '--region'
      - europe-west3
images:
  - 'europe-west1-docker.pkg.dev/progress-january2024/evgeni/personapi:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
