version: '3.9'

services:
  app:
    image: 'personapi:1.0.3'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/personapi
      - SPRING_DATASOURCE_USERNAME=personapi
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=personapi
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - '5444:5432'
volumes:
  postgres-data:
